# Generated by Django 5.0.3 on 2024-03-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='cab_status',
            field=models.BooleanField(),
        ),
    ]
