# Generated by Django 5.0.3 on 2024-03-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_cab_cab_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
